#!/usr/bin/env fish

set base "$PWD/archives"

set group $argv[1]
if test -n "$group"
    set base "$base/$group"
end

mkdir -p "$base"

set idx (printf "%03d" (math (count $base/*.cpp) + 1))

echo "Index: $idx"
read -P "ID: " id
read -P "Name (optional): " name

if test -n "$name"
    set file (printf "$base/%s_%s_%s.cpp" $idx $id $name)
else
    set file (printf "$base/%s_%s.cpp" $idx $id)
end

set tempfile (mktemp)
echo "Problem: (editing in \$EDITOR...)"
$EDITOR $tempfile
for line in (cat $tempfile)
    if test -z "$line"
        echo // >>$file
        continue
    end
    echo "// $line" >>$file
end
rm -f $tempfile

echo >>$file
echo "// clang-format off" >>$file

echo >>$file
echo "// Sample Input" >>$file
for line in (cat ./src/in.txt)
    echo "// $line" >>$file
end

echo >>$file
echo "// Sample Output" >>$file
for line in (cat ./src/out.txt)
    echo "// $line" >>$file
end

echo >>$file
echo "// clang-format on" >>$file

echo >>$file
for line in (cat ./src/main.cpp)
    echo $line >>$file
end

echo "Formatting..."
clang-format -i $file
