#!/usr/bin/env fish

if not test -d ./archives
    echo "Error: ./archives directory does not exist."
    return 1
end

if test (count $argv) -eq 0
    set file (fd --type file . ./archives | fzf --preview-window "right,60%,border-left")

    if test -z "$file"
        echo "Error: No file selected."
        return 1
    end
else if test (count $argv) -eq 1
    set -l id $argv[1]
    set -l files (fd --type file --regex "^([0-9]+_)?$id(_.+)?\\.cpp\$" ./archives)

    if test (count $files) -eq 0
        echo "Error: No files found with id: $id."
        return 1
    end

    if test (count $files) -eq 1
        set file $files[1]
    else
        set file (echo $files | string replace -ar " " "\n" | fzf --preview-window "right,60%,border-left")
    end
else
    echo "Error: Too many arguments."
    return 1
end

mkdir -p ./src
./scripts/new -yn

set inner_sample_input 0
set inner_sample_output 0
set inner_code 0

for line in (cat $file)
    if string match -rq '^// Sample Input$' $line
        set inner_sample_input 1
        continue
    end

    if string match -rq '^// Sample Output$' $line
        set inner_sample_output 1
        continue
    end

    if test $inner_sample_input -eq 1
        if string match -rq '^$' $line
            set inner_sample_input 0
            continue
        end
        string replace -r '^// ?' '' $line >>./src/in.txt
        continue
    end

    if test $inner_sample_output -eq 1
        if string match -rq '^$' $line
            set inner_sample_output 0
            continue
        end
        string replace -r '^// ?' '' $line >>./src/out.txt
        continue
    end

    if string match -rq '^//.*$' $line
        continue
    end

    if not string match -rq '^$' $line
        and not string match -rq '^// clang-format on$' $line
        set inner_code 1
    end

    if test $inner_code -eq 1
        echo $line >>./src/main.cpp
    end
end

echo "File $(set_color green)$file$(set_color normal) has been checked out to ./src/main.cpp"
